// Additional UI translations injected into the app's L{} table by gen_app.mjs.
// Keys mirror the handoff's tr/en dicts exactly. brand "app" stays "Zikirci".
// Arabic is rendered RTL by the companion script (document.dir).
// ponytail: module.exports (not `export default`) because root package.json is type:commonjs;
// gen_app.mjs imports this via ESM→CJS interop. Keeps the .js filename CLAUDE.md references.
module.exports = {
  ar: {app:'الذّاكِر',sayac:'العداد',kutup:'مكتبتي',stat:'الإحصائيات',ayar:'الإعدادات',
    kutupSub:'اختر وأدر أذكارك',statSub:'تابع تقدمك الروحي',ayarSub:'خصّص تجربتك',
    hedef:'الهدف',kalan:'المتبقي',serbest:'حر',devam:'متابعة',basla:'ابدأ',yeni:'ذكر جديد',
    ad:'اسم الذكر',hedefPh:'الهدف (فارغ = حر)',kategori:'الفئة',sesZikir:'صوت لهذا الذكر',kaydet:'حفظ',iptal:'إلغاء',
    hepsi:'الكل',gunlukK:'يومي',namaz:'بعد الصلاة',ozel:'خاص',
    gunluk:'يومي',haftalik:'أسبوعي',aylik:'شهري',
    yogunluk:'كثافة الذكر',az:'قليل',cok:'كثير',
    toplam:'إجمالي الذكر',ort:'المعدل اليومي',seri:'أطول سلسلة',sure:'الوقت المنقضي',
    buHafta:'+15% هذا الأسبوع',istikrar:'منتظم',gun:'يوم',saat:'ساعة',aktifSeri:'نشط الآن!',haftaTop:'إجمالي هذا الأسبوع',
    aktivite:'النشاط عبر الزمن',dagilim:'توزيع الذكر',
    gorunum:'المظهر',tema:'السمة',dil:'اللغة',yakinda:'قريباً',
    sesTitresim:'الصوت والاهتزاز',sesli:'التنبيهات الصوتية',sesliDesc:'تشغيل الصوت عند نقاط التنبيه',
    titresim:'الاهتزاز',titresimDesc:'اهتزاز عند اللمس والتنبيهات',
    ekranKapali:'العد بأزرار الصوت',ekranKapaliDesc:'العد بأزرار الصوت والشاشة مغلقة',
    sesSev:'مستوى الصوت',tikSes:'صوت النقر',yumusak:'نقرة ناعمة',damla:'قطرة',tespih:'مسبحة',hicSes:'بلا',tahta:'خشب',can:'جرس',
    kilit:'قفل',kilitli:'مقفل',kilitAcikla:'اضغط مطولاً لفتح القفل',yerlesim:'التخطيط',normal:'عادي',merkez:'وسط',
    libNav:'الأذكار',statNav:'إحصاء',ortaSid:'متوسط',adDegis:'اسم الذكر',sil:'حذف',sabitle:'تثبيت',sabitli:'مثبّت',
    tasarim:'تصميم العدّاد',dKlasik:'كلاسيكي',dBirlesik:'موحّد',dTespih:'مسبحة',
    taslar:'نقاط التنبيه',taslarDesc:'الأعداد التي تُشغّل الصوت والاهتزاز — فعّل كلاً على حدة',
    sayacBtn:'العداد والزر',presetler:'إعدادات جاهزة',klasik:'كلاسيكي',tamG:'عرض كامل',mini:'صغير',solak:'اليد اليسرى',saglak:'اليد اليمنى',sifirlaA:'تصفير',
    anim:'حركة العداد',halka:'حلقة',dalga:'موجة',dolum:'امتلاء',sekilM:'تحول الشكل',
    renk:'لون الزر',vurgu:'مميز',notr:'محايد',murekkep:'حبر',
    sekil:'شكل الزر',daire:'دائرة',yumKare:'مربع ناعم',kare:'مربع',
    boyut:'حجم الزر',tam:'كامل',konum:'موضع الزر',sol:'يسار',orta:'وسط',sag:'يمين',
    ozelT:'مخصص',genislik:'العرض',yukseklik:'الارتفاع',altBosluk:'المسافة السفلية',
    sayacSekil:'شكل العداد',temaOto:'السمة',telefon:'هاتف',telefonY:'هاتف أفقي',tabletT:'لوحي',tabletY:'لوحي أفقي',
    hatir:'التذكيرات',yeniHatir:'تذكير جديد',etiket:'التسمية (مثل الصباح)',ekle:'إضافة',
    duzenle:'قيمة العداد',duzenleDesc:'اضبط العداد على أي قيمة',
    hedefAyar:'تعيين الهدف',hedefDesc:'عدد الهدف والاتجاه',yukari:'عد تصاعدي',geriSay:'عد تنازلي',kalanG:'إظهار المتبقي والنسبة',
    sifirla:'تصفير',hedefBtn:'الهدف',haptik:'اهتزاز',ozellestir:'تخصيص',
    zikirAyar:'إعدادات الذكر',zikirAyarDesc:'صوت واهتزاز خاص بهذا الذكر',
    vibStil:'نمط الاهتزاز',kisa:'قصير',cift:'مزدوج',uzun:'طويل',
    siddet:'شدة الاهتزاز',hafif:'خفيف',guclu:'قوي',
    hedefTamam:'اكتمل الهدف',bin:'ألف',tamamlandi:'اكتمل',aktifHatir:'تذكير نشط',
    yardim:'المساعدة والدعم',yardimD:'راسلنا عبر البريد',puanla:'قيّم على Play Store',puanlaD:'تقييم 5 نجوم يساعدنا كثيراً',
    her100:'كل 100',
    dev:' · v1.0 · ',
    dayRows:['إث','أر','جم'],
    dLabels:['00','06','12','18','23'],wLabels:['إث','ثل','أر','خم','جم','سب','أح'],mLabels:['ي','ف','م','أ','م','ي','ي','أ','س','أ','ن','د']},
  id: {app:'Dhikrer',sayac:'Penghitung',kutup:'Pustaka Saya',stat:'Statistik',ayar:'Pengaturan',
    kutupSub:'Pilih dan kelola zikir Anda',statSub:'Pantau kemajuan spiritual Anda',ayarSub:'Sesuaikan pengalaman Anda',
    hedef:'Target',kalan:'Sisa',serbest:'Bebas',devam:'Lanjutkan',basla:'Mulai',yeni:'Zikir Baru',
    ad:'Nama zikir',hedefPh:'Target (kosong = bebas)',kategori:'Kategori',sesZikir:'Suara untuk zikir ini',kaydet:'Simpan',iptal:'Batal',
    hepsi:'Semua',gunlukK:'Harian',namaz:'Setelah Salat',ozel:'Khusus',
    gunluk:'Harian',haftalik:'Mingguan',aylik:'Bulanan',
    yogunluk:'Intensitas Zikir',az:'Sedikit',cok:'Banyak',
    toplam:'Total Zikir',ort:'Rata-rata Harian',seri:'Rentetan Terpanjang',sure:'Waktu Terpakai',
    buHafta:'+15% minggu ini',istikrar:'Konsisten',gun:'hari',saat:'jam',aktifSeri:'Aktif sekarang!',haftaTop:'Total minggu ini',
    aktivite:'Aktivitas dari Waktu ke Waktu',dagilim:'Distribusi Zikir',
    gorunum:'Tampilan',tema:'Tema',dil:'Bahasa',yakinda:'segera',
    sesTitresim:'Suara & Getaran',sesli:'Peringatan Suara',sesliDesc:'Mainkan suara di titik notifikasi',
    titresim:'Getaran (Haptic)',titresimDesc:'Bergetar saat ketuk dan peringatan',
    ekranKapali:'Hitung dengan tombol volume',ekranKapaliDesc:'Hitung dengan tombol volume saat layar mati',
    sesSev:'Volume',tikSes:'Suara Ketuk',yumusak:'Ketuk Halus',damla:'Tetes',tespih:'Tasbih',hicSes:'Tidak Ada',tahta:'Kayu',can:'Lonceng',
    kilit:'Kunci',kilitli:'Terkunci',kilitAcikla:'Tahan untuk membuka',yerlesim:'Tata Letak',normal:'Normal',merkez:'Tengah',
    libNav:'Zikir',statNav:'Statistik',ortaSid:'Sedang',adDegis:'Nama zikir',sil:'Hapus',sabitle:'Sematkan',sabitli:'Disematkan',
    tasarim:'Desain Penghitung',dKlasik:'Klasik',dBirlesik:'Menyatu',dTespih:'Tasbih',
    taslar:'Titik Notifikasi',taslarDesc:'Hitungan yang memicu suara & getaran — atur satu per satu',
    sayacBtn:'Penghitung & Tombol',presetler:'Prasetel',klasik:'Klasik',tamG:'Lebar Penuh',mini:'Mini',solak:'Tangan Kiri',saglak:'Tangan Kanan',sifirlaA:'Setel Ulang',
    anim:'Animasi Penghitung',halka:'Cincin',dalga:'Gelombang',dolum:'Isian',sekilM:'Ubah Bentuk',
    renk:'Warna Tombol',vurgu:'Aksen',notr:'Netral',murekkep:'Tinta',
    sekil:'Bentuk Tombol',daire:'Lingkaran',yumKare:'Kotak Halus',kare:'Kotak',
    boyut:'Ukuran Tombol',tam:'Penuh',konum:'Posisi Tombol',sol:'Kiri',orta:'Tengah',sag:'Kanan',
    ozelT:'Khusus',genislik:'Lebar',yukseklik:'Tinggi',altBosluk:'Jarak Bawah',
    sayacSekil:'Bentuk Penghitung',temaOto:'Tema',telefon:'Ponsel',telefonY:'Ponsel Lanskap',tabletT:'Tablet',tabletY:'Tablet Lanskap',
    hatir:'Pengingat',yeniHatir:'Pengingat baru',etiket:'Label (mis. Pagi)',ekle:'Tambah',
    duzenle:'Nilai Penghitung',duzenleDesc:'Setel penghitung ke nilai apa pun',
    hedefAyar:'Setel Target',hedefDesc:'Jumlah target dan arah',yukari:'Hitung Naik',geriSay:'Hitung Mundur',kalanG:'Tampilkan sisa & persen',
    sifirla:'Setel Ulang',hedefBtn:'Target',haptik:'Getaran',ozellestir:'Sesuaikan',
    zikirAyar:'Pengaturan Zikir',zikirAyarDesc:'Suara dan getaran untuk zikir ini',
    vibStil:'Gaya Getaran',kisa:'Pendek',cift:'Ganda',uzun:'Panjang',
    siddet:'Intensitas Getaran',hafif:'Ringan',guclu:'Kuat',
    hedefTamam:'Target Tercapai',bin:'rb',tamamlandi:'selesai',aktifHatir:'pengingat aktif',
    yardim:'Bantuan & Dukungan',yardimD:'Kirim email ke kami',puanla:'Beri Nilai di Play Store',puanlaD:'Nilai 5 bintang sangat membantu',
    her100:'Tiap 100',
    dev:' · v1.0 · ',
    dayRows:['Sen','Rab','Jum'],
    dLabels:['00','06','12','18','23'],wLabels:['Sen','Sel','Rab','Kam','Jum','Sab','Min'],mLabels:['J','F','M','A','M','J','J','A','S','O','N','D']},
  hi: {app:'Dhikrer',sayac:'काउंटर',kutup:'मेरी लाइब्रेरी',stat:'आँकड़े',ayar:'सेटिंग्स',
    kutupSub:'अपने ज़िक्र चुनें और प्रबंधित करें',statSub:'अपनी आध्यात्मिक प्रगति देखें',ayarSub:'अपना अनुभव अनुकूलित करें',
    hedef:'लक्ष्य',kalan:'शेष',serbest:'मुक्त',devam:'जारी रखें',basla:'शुरू करें',yeni:'नया ज़िक्र',
    ad:'ज़िक्र नाम',hedefPh:'लक्ष्य (खाली = मुक्त)',kategori:'श्रेणी',sesZikir:'इस ज़िक्र के लिए ध्वनि',kaydet:'सहेजें',iptal:'रद्द करें',
    hepsi:'सभी',gunlukK:'दैनिक',namaz:'नमाज़ के बाद',ozel:'कस्टम',
    gunluk:'दैनिक',haftalik:'साप्ताहिक',aylik:'मासिक',
    yogunluk:'ज़िक्र तीव्रता',az:'कम',cok:'ज़्यादा',
    toplam:'कुल ज़िक्र',ort:'दैनिक औसत',seri:'सबसे लंबी श्रृंखला',sure:'बीता समय',
    buHafta:'+15% इस सप्ताह',istikrar:'नियमित',gun:'दिन',saat:'घंटे',aktifSeri:'अभी सक्रिय!',haftaTop:'इस सप्ताह कुल',
    aktivite:'समय के साथ गतिविधि',dagilim:'ज़िक्र वितरण',
    gorunum:'रूप',tema:'थीम',dil:'भाषा',yakinda:'जल्द ही',
    sesTitresim:'ध्वनि और कंपन',sesli:'ध्वनि अलर्ट',sesliDesc:'सूचना बिंदुओं पर ध्वनि बजाएँ',
    titresim:'कंपन (हैप्टिक)',titresimDesc:'टैप और अलर्ट पर कंपन',
    ekranKapali:'वॉल्यूम कुंजी से गिनती',ekranKapaliDesc:'स्क्रीन बंद होने पर वॉल्यूम कुंजियों से गिनें',
    sesSev:'वॉल्यूम',tikSes:'क्लिक ध्वनि',yumusak:'मृदु टिक',damla:'बूँद',tespih:'तस्बीह',hicSes:'कोई नहीं',tahta:'लकड़ी',can:'घंटी',
    kilit:'लॉक',kilitli:'लॉक',kilitAcikla:'अनलॉक करने के लिए दबाए रखें',yerlesim:'लेआउट',normal:'सामान्य',merkez:'केंद्र',
    libNav:'ज़िक्र',statNav:'आँकड़े',ortaSid:'मध्यम',adDegis:'ज़िक्र नाम',sil:'हटाएँ',sabitle:'पिन',sabitli:'पिन किया',
    tasarim:'काउंटर डिज़ाइन',dKlasik:'क्लासिक',dBirlesik:'एकीकृत',dTespih:'तस्बीह',
    taslar:'सूचना बिंदु',taslarDesc:'वे गिनतियाँ जो ध्वनि और कंपन करती हैं — प्रत्येक अलग से चालू/बंद',
    sayacBtn:'काउंटर और बटन',presetler:'प्रीसेट',klasik:'क्लासिक',tamG:'पूरी चौड़ाई',mini:'मिनी',solak:'बायाँ हाथ',saglak:'दायाँ हाथ',sifirlaA:'रीसेट',
    anim:'काउंटर एनिमेशन',halka:'वलय',dalga:'लहर',dolum:'भराव',sekilM:'आकार बदलाव',
    renk:'बटन रंग',vurgu:'एक्सेंट',notr:'तटस्थ',murekkep:'स्याही',
    sekil:'बटन आकार',daire:'वृत्त',yumKare:'मृदु वर्ग',kare:'वर्ग',
    boyut:'बटन आकार',tam:'पूर्ण',konum:'बटन स्थिति',sol:'बाएँ',orta:'मध्य',sag:'दाएँ',
    ozelT:'कस्टम',genislik:'चौड़ाई',yukseklik:'ऊँचाई',altBosluk:'नीचे का अंतर',
    sayacSekil:'काउंटर आकार',temaOto:'थीम',telefon:'फ़ोन',telefonY:'फ़ोन लैंडस्केप',tabletT:'टैबलेट',tabletY:'टैबलेट लैंडस्केप',
    hatir:'रिमाइंडर',yeniHatir:'नया रिमाइंडर',etiket:'लेबल (जैसे सुबह)',ekle:'जोड़ें',
    duzenle:'काउंटर मान',duzenleDesc:'काउंटर को किसी भी मान पर सेट करें',
    hedefAyar:'लक्ष्य सेट करें',hedefDesc:'लक्ष्य संख्या और दिशा',yukari:'ऊपर गिनें',geriSay:'उलटी गिनती',kalanG:'शेष और प्रतिशत दिखाएँ',
    sifirla:'रीसेट',hedefBtn:'लक्ष्य',haptik:'कंपन',ozellestir:'अनुकूलित करें',
    zikirAyar:'ज़िक्र सेटिंग्स',zikirAyarDesc:'इस ज़िक्र के लिए ध्वनि और कंपन',
    vibStil:'कंपन शैली',kisa:'छोटा',cift:'दोहरा',uzun:'लंबा',
    siddet:'कंपन तीव्रता',hafif:'हल्का',guclu:'तेज़',
    hedefTamam:'लक्ष्य पूर्ण',bin:'हज़ार',tamamlandi:'पूर्ण',aktifHatir:'रिमाइंडर सक्रिय',
    yardim:'सहायता और समर्थन',yardimD:'हमें ईमेल भेजें',puanla:'Play Store पर रेटिंग दें',puanlaD:'5-स्टार रेटिंग बहुत मदद करती है',
    her100:'हर 100',
    dev:' · v1.0 · ',
    dayRows:['सोम','बुध','शुक्र'],
    dLabels:['00','06','12','18','23'],wLabels:['सोम','मंगल','बुध','गुरु','शुक्र','शनि','रवि'],mLabels:['ज','फ','मा','अ','म','जू','जु','अ','सि','अ','न','दि']},
  zh: {app:'Dhikrer',sayac:'计数器',kutup:'我的库',stat:'统计',ayar:'设置',
    kutupSub:'选择并管理你的赞念',statSub:'追踪你的心灵进展',ayarSub:'自定义你的体验',
    hedef:'目标',kalan:'剩余',serbest:'自由',devam:'继续',basla:'开始',yeni:'新赞念',
    ad:'赞念名称',hedefPh:'目标（留空 = 自由）',kategori:'类别',sesZikir:'此赞念的声音',kaydet:'保存',iptal:'取消',
    hepsi:'全部',gunlukK:'每日',namaz:'礼拜后',ozel:'自定义',
    gunluk:'每日',haftalik:'每周',aylik:'每月',
    yogunluk:'赞念强度',az:'少',cok:'多',
    toplam:'赞念总数',ort:'日均',seri:'最长连续',sure:'已用时间',
    buHafta:'本周 +15%',istikrar:'稳定',gun:'天',saat:'小时',aktifSeri:'现在活跃！',haftaTop:'本周总计',
    aktivite:'随时间的活动',dagilim:'赞念分布',
    gorunum:'外观',tema:'主题',dil:'语言',yakinda:'即将',
    sesTitresim:'声音与震动',sesli:'声音提示',sesliDesc:'在提示点播放声音',
    titresim:'震动（触感）',titresimDesc:'点击和提示时震动',
    ekranKapali:'用音量键计数',ekranKapaliDesc:'息屏时用音量键计数',
    sesSev:'音量',tikSes:'点击声音',yumusak:'轻点',damla:'水滴',tespih:'念珠',hicSes:'无',tahta:'木鱼',can:'铃',
    kilit:'锁定',kilitli:'已锁定',kilitAcikla:'长按解锁',yerlesim:'布局',normal:'普通',merkez:'居中',
    libNav:'赞念',statNav:'统计',ortaSid:'中',adDegis:'赞念名称',sil:'删除',sabitle:'置顶',sabitli:'已置顶',
    tasarim:'计数器样式',dKlasik:'经典',dBirlesik:'合一',dTespih:'念珠',
    taslar:'提示点',taslarDesc:'触发声音和震动的计数——逐个开关',
    sayacBtn:'计数器与按钮',presetler:'预设',klasik:'经典',tamG:'全宽',mini:'迷你',solak:'左手',saglak:'右手',sifirlaA:'重置',
    anim:'计数器动画',halka:'圆环',dalga:'波浪',dolum:'填充',sekilM:'形状变换',
    renk:'按钮颜色',vurgu:'强调色',notr:'中性',murekkep:'墨色',
    sekil:'按钮形状',daire:'圆形',yumKare:'圆角方形',kare:'方形',
    boyut:'按钮大小',tam:'全部',konum:'按钮位置',sol:'左',orta:'中',sag:'右',
    ozelT:'自定义',genislik:'宽度',yukseklik:'高度',altBosluk:'底部间距',
    sayacSekil:'计数器形状',temaOto:'主题',telefon:'手机',telefonY:'手机横屏',tabletT:'平板',tabletY:'平板横屏',
    hatir:'提醒',yeniHatir:'新提醒',etiket:'标签（如 早晨）',ekle:'添加',
    duzenle:'计数值',duzenleDesc:'将计数器设为任意值',
    hedefAyar:'设置目标',hedefDesc:'目标数量和方向',yukari:'正计数',geriSay:'倒计数',kalanG:'显示剩余和百分比',
    sifirla:'重置',hedefBtn:'目标',haptik:'震动',ozellestir:'自定义',
    zikirAyar:'赞念设置',zikirAyarDesc:'此赞念的声音和震动',
    vibStil:'震动样式',kisa:'短',cift:'双',uzun:'长',
    siddet:'震动强度',hafif:'轻',guclu:'强',
    hedefTamam:'目标完成',bin:'千',tamamlandi:'完成',aktifHatir:'个提醒已启用',
    yardim:'帮助与支持',yardimD:'给我们发邮件',puanla:'在 Play Store 评分',puanlaD:'五星好评对我们帮助很大',
    her100:'每 100',
    dev:' · v1.0 · ',
    dayRows:['一','三','五'],
    dLabels:['00','06','12','18','23'],wLabels:['一','二','三','四','五','六','日'],mLabels:['1','2','3','4','5','6','7','8','9','10','11','12']}
};
